# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2610551f107e04d38b85a6f1b19ed7ba3fa5ab1f03602e6fe441fdb9f3cba429e31ce565171c7b01648037d06b38b67e22224be8c4d79a29e994f1d18a3757bc

test:
  secret_key_base: 20dab256a384840f81b9545896dc22ce42436e57e6b1bd6a89fc9b5735a99fa681acd7b92233f2f6a0d3dda98d2d5915080b2a3e7503dc993606d9254384d690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
